### PR TITLE
Allow 64-bit enumeration values

### LINKED ISSUE #72: overflow in enumeration value: 18446744069414584320
```
/usr/include/linux/perf_event.h:230:25: overflow in enumeration value: 18446744069414584320
```

Line 230 reads:

```
enum {
  PERF_TXN_ABORT_MASK  = (0xffffffffULL << 32)
};
```

Fix is incoming.

### PR DESCRIPTION
**Pull request by pwaller**
Fixes #72.

### CODE REVIEW

**Comment by pwaller** [comment]
Hm. Well, I'd obviously like them so that I can parse `linux/perf_event.h`, which contains them. :)

I don't know where that puts a patch like this. Is it another `Opt`?

**Comment by pwaller** [comment]
How about `EnableLongLongEnumValues`?

**Comment by cznic** [comment]
> How about EnableLongLongEnumValues?

Maybe too specific. The option should probably enable use of any integral type. (In doubts I use to look what gcc accepts when no `--pedantic` is used.)

**Comment by cznic** [comment]
There's also `char`, `short` and their signed/unsigned variants.

But maybe something like `EnableLongLongEnumValues` is good enough with the godoc saying it applies to `unsigned long long` as well. Or `EnableWideEnumValues` perhaps?

Your call, no strong opinion here.

**Comment by pwaller** [comment]
Well, the standard just says:

> The expression that defines the value of an enumeration constant shall be an integer
constant expression that has a value representable as an int.

So I interpret that we do not need to do anything special for char/short, just wide, so I'm happy to go for `EnableWideEnumValues`.

The patch then would define `intSize := m.Items[Int].Size`, which would be set to `m.Items[LongLong].Size` if `EnableWideEnumValues` is enabled. Since `toInt` is only used for enum values, I suggest the function is renamed to `enumValueToInt` avoid confusion. I wasn't aware it was specific to enums until I saw a comment somewhere on the issue tracker.

How does that sound?

A point of confusion for me, why is the switch switching over `m.Items[Int].Size` anyway? In what sense is that a variable, is it configurable? If it is configurable, maybe the correct solution is not any kind of patch but for me to just configure it to use `sizeof(int) == 8`.

**Comment by cznic** [comment]
> How does that sound?

SGTM

> A point of confusion for me, why is the switch switching over m.Items[Int].Size anyway?

Possibly a historical artefact, it may have been used/planned to be used for something else, but I do not recall anything specific.

**Comment by pwaller** [comment]
Hmm. How do I access the `tweaks` from the `Model`? I guess I have to pass them into `toInt` as an additional parameter. I'll do that unless you point out another way.

**Comment by pwaller** [comment]
I have implemented `EnableWideEnumValues` and force pushed. I pass the whole tweaks structure through to `toInt` (now called `enumValueToInt`). PTAL.

**Comment by cznic** [comment]
> Hmm. How do I access the tweaks from the Model? I guess I have to pass them into toInt as an additional parameter. I'll do that unless you point out another way.

Okay, alternatively add a private `tweaks *tweaks` field to `Model` and set it around [here](https://github.com/cznic/cc/blob/533ca70c55a2970885094ae5e68eb27588f7ffc7/cc.go#L449). (`Model` instances are documented to be non-reusable.)

**Comment by pwaller** [comment]
> Okay, alternatively add a private tweaks *tweaks field to Model and set it around here. (Model instances are documented to be non-reusable.)
Done.

**Pull request merged**
