### PR TITLE
Fix os-specific const in HostCppConfig, resolves #58

### LINKED ISSUE #58: No /dev/null under Windows
Hi! I discovered this issue while using CC host config option under Windows MinGW environment:

```go
func HostCppConfig(cpp string, opts ...string) (predefined string, includePaths, sysIncludePaths []string, err error) {
	args := append(append([]string{"-dM"}, opts...), "/dev/null")
...
```
Uses `/dev/null` that's not available under windows. It must be `nul` instead.
This bug is easy to fix, however I want your opinion because this is design-specific.

I would use `runtime.GOOS`.

### PR DESCRIPTION
**Pull request by xlab**

### CODE REVIEW

**Comment by xlab** [comment]
Hold on, don't merge yet please.

**Comment by xlab** [comment]
Ok, so under `Cygwin GCC 4.9.2 (i686-pc-cygwin)` this breaks stuff, but who cares about Cygwin :/

**Comment by cznic** [comment]
Please merge it by yourself when you find it correct, I have still few hundreds of km ahead of me.

**Comment by cznic** [comment]
Hi Max,

thank you for your work and analysis.

I don't know how important is to support Cygwin, but if it would be easy _not to_ break Cygwin then it would be certainly preferable.

What about extending `HostConfig` by first looking at the output of `cpp --version`, look for some specific Cygwin signature and special case it?

> cpp -v output that doesn't parse either way

I think we can avoid the parsing problem by unconditionally doing `stings.Replace(s, "\r", "", -1)` as a preparation step before `string.Split`.

What do you think?

**Comment by xlab** [comment]
Cygwin parsing doesn't work either with `\r\n` or `\n` that's the problem. I could provide a fixture for you. Hold a sec.

**Comment by xlab** [comment]
```
$ cpp -v /dev/null
Using built-in specs.
COLLECT_GCC=cpp
Target: i686-pc-cygwin
Configured with: /cygdrive/i/szsz/tmpp/gcc/gcc-4.9.2-3.i686/src/gcc-4.9.2/configure --srcdir=/cygdrive/i/szsz/tmpp/gcc/gcc-4.9.2-3.i686/src/gcc-4.9.2 --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/libexec --datadir=/usr/share --localstatedir=/var --sysconfdir=/etc --libdir=/usr/lib --datarootdir=/usr/share --docdir=/usr/share/doc/gcc --htmldir=/usr/share/doc/gcc/html -C --build=i686-pc-cygwin --host=i686-pc-cygwin --target=i686-pc-cygwin --without-libiconv-prefix --without-libintl-prefix --libexecdir=/usr/lib --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --enable-bootstrap --enable-__cxa_atexit --with-dwarf2 --with-arch=i686 --with-tune=generic --disable-sjlj-exceptions --enable-languages=ada,c,c++,fortran,java,lto,objc,obj-c++ --enable-graphite --enable-threads=posix --enable-libatomic --enable-libgomp --disable-libitm --enable-libquadmath --enable-libquadmath-support --enable-libssp --enable-libada --enable-libjava --enable-libgcj-sublibs --disable-java-awt --disable-symvers --with-ecj-jar=/usr/share/java/ecj.jar --with-gnu-ld --with-gnu-as --with-cloog-include=/usr/include/cloog-isl --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id
Thread model: posix
gcc version 4.9.2 (GCC)
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=i686'
 /usr/lib/gcc/i686-pc-cygwin/4.9.2/cc1.exe -E -quiet -v -Dunix -idirafter /usr/lib/gcc/i686-pc-cygwin/4.9.2/../../../../include/w32api -idirafter /usr/lib/gcc/i686-pc-cygwin/4.9.2/../../../../i686-pc-cygwin/lib/../../include/w32api /dev/null -mtune=generic -march=i686
ignoring nonexistent directory "/usr/local/include"
ignoring nonexistent directory "/usr/lib/gcc/i686-pc-cygwin/4.9.2/../../../../i686-pc-cygwin/include"
ignoring duplicate directory "/usr/lib/gcc/i686-pc-cygwin/4.9.2/../../../../i686-pc-cygwin/lib/../../include/w32api"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/i686-pc-cygwin/4.9.2/include
 /usr/lib/gcc/i686-pc-cygwin/4.9.2/include-fixed
 /usr/include
 /usr/lib/gcc/i686-pc-cygwin/4.9.2/../../../../include/w32api
End of search list.
# 1 "/dev/null"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/dev/null"
COMPILER_PATH=/usr/lib/gcc/i686-pc-cygwin/4.9.2/:/usr/lib/gcc/i686-pc-cygwin/4.9.2/:/usr/lib/gcc/i686-pc-cygwin/:/usr/lib/gcc/i686-pc-cygwin/4.9.2/:/usr/lib/gcc/i686-pc-cygwin/:/usr/lib/gcc/i686-pc-cygwin/4.9.2/../../../../i686-pc-cygwin/bin/
LIBRARY_PATH=/usr/lib/gcc/i686-pc-cygwin/4.9.2/:/usr/lib/gcc/i686-pc-cygwin/4.9.2/../../../../i686-pc-cygwin/lib/:/usr/lib/gcc/i686-pc-cygwin/4.9.2/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=i686'
```

**Comment by cznic** [comment]
@xlab 

I've added a test parsing the Cygwin output you've provided above and I fail to get a problem. Please take a look at https://github.com/cznic/cc/commit/9c457f88e14e1cafb443a91adb2b593fec1ce970 and help to make the test show the problem. Thank you.

FTR, ATM:

```bash
jnml@4670:~/src/github.com/cznic/cc$ git status 
On branch issue60
Your branch is up-to-date with 'origin/issue60'.
nothing to commit, working directory clean
jnml@4670:~/src/github.com/cznic/cc$ git log -1
commit 9c457f88e14e1cafb443a91adb2b593fec1ce970
Author: Jan Mercl <0xjnml@gmail.com>
Date:   Sun Nov 6 17:59:31 2016 +0100

    Add Cygwin output parsing test. Updates #60.
jnml@4670:~/src/github.com/cznic/cc$ go test -v -run 60
=== RUN   TestIssue60
--- PASS: TestIssue60 (0.00s)
	all_test.go:2597: 
		IncludePaths:
		
		SysIncludePaths:
		[]string{ // len 4
		· 0: "/usr/lib/gcc/i686-pc-cygwin/4.9.2/include",
		· 1: "/usr/lib/gcc/i686-pc-cygwin/4.9.2/include-fixed",
		· 2: "/usr/include",
		· 3: "/usr/lib/gcc/i686-pc-cygwin/4.9.2/../../../../include/w32api",
		}
PASS
ok  	github.com/cznic/cc	0.002s
jnml@4670:~/src/github.com/cznic/cc$ 
```

**Comment by cznic** [comment]
@xlab Gentle ping.

**Comment by xlab** [comment]
I propose to merge this PR, and if any issue comes up with Cygwin, we will resolve it in another PR/issue.

**Pull request closed without merging**
