### PR TITLE
Add times.h and tcp.h for linux_arm.

### PR DESCRIPTION
**Pull request by kortschak**
@cznic Please take a look.

### CODE REVIEW

**Review by cznic — COMMENTED** [review]
I think we need to add `"netinet/tcp"` to the list here https://github.com/cznic/cc/blob/b5e2186b9dda8102bd3a831a89d4550de37fa079/v2/headers/generator.go#L67. WDYT?

**Comment by cznic** [comment]
FTR, it should be also possible to add a ccgo option, for example on my system, `-I /usr/include` as long as this is needed only get the proper constants etc., ie. to consume a code-less header.

**Comment by kortschak** [comment]
I think adding "netinit/tcp" into needs sounds reasonable.

**Review by cznic — APPROVED** [review]
LGTM with or without the addition to headers/generator.go line as I can add it later by myself.

Please commit to the master branch, thank you.

**Comment by kortschak** [comment]
I'm building ccgo on the pi (zero) at the moment, so I'll add the line when that's done, then merge. It will likely take a while.

**Pull request merged**
